apiVersion: apps/v1
kind: Deployment
metadata:
  name: flatbuddy-backend
  namespace: flatbuddy-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flatbuddy-backend
  template:
    metadata:
      labels:
        app: flatbuddy-backend
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
        - name: flatbuddy-backend
          image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/flatbuddy-backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
---
apiVersion: v1
kind: Service
metadata:
  name: flatbuddy-backend
  namespace: flatbuddy-ns
spec:
  selector:
    app: flatbuddy-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
