apiVersion: apps/v1
kind: Deployment
metadata:
  name: flatbuddy-frontend
  namespace: flatbuddy-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flatbuddy-frontend
  template:
    metadata:
      labels:
        app: flatbuddy-frontend
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
        - name: flatbuddy-frontend
          image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/flatbuddy-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flatbuddy-frontend
  namespace: flatbuddy-ns
spec:
  selector:
    app: flatbuddy-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
